### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by stegaBOB** [regolith-labs/dioxus-wallet-adapter#3]
It doesn't look like there's a license anywhere in this repo (nor in the Cargo.toml). Unless I'm mistaken, that technically means it's not open source yet and isn't usable. Would you guys be willing to license this under MIT or Apache-2.0 (or better yet, dual license!), and include that in a license file? Thanks for all this awesome work!!

**Comment by HardhatChad** [comment]
Thanks for flagging. Just added
